# Generated by Django 5.2.17 on 2026-09-01 13:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=80)),
                ('entity', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_number', models.CharField(max_length=30, unique=True, verbose_name='nómina')),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('area', models.CharField(blank=True, max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=30, verbose_name='identificador')),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=80, unique=True, verbose_name='número de parte')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('diameter', models.CharField(blank=True, max_length=40)),
                ('unit_weight_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(blank=True, db_index=True, max_length=50)),
                ('movement_type', models.CharField(choices=[('INVENTORY', 'Inventario'), ('PROGRAM', 'Programa'), ('SURPLUS', 'Sobrante'), ('ORDER', 'Orden')], max_length=12)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('program', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('occurred_at', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
                ('legacy_source', models.CharField(blank=True, max_length=80)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.employee')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.part')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('surplus', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('real', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='operations.part')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.process')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(max_length=40, unique=True)),
                ('program', models.CharField(db_index=True, max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('required_date', models.DateField(blank=True, null=True)),
                ('line', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('COMPLETE', 'Completada'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=12)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('loaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.employee')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.part')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkInProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(max_length=40, unique=True)),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('status', models.CharField(choices=[('ACTIVE', 'Procesando'), ('CLOSED', 'Cerrada')], default='ACTIVE', max_length=12)),
                ('started_at', models.DateTimeField()),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='operations.machine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='operations.productionorder')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_work', to='operations.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(max_length=40, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('weight_kg', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('closed_at', models.DateTimeField()),
                ('shift', models.CharField(blank=True, max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_closes', to='operations.employee')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closes', to='operations.workinprocess')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('PROGRAM', 'Programa'), ('PROCESS', 'Proceso')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='operations.inventory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('inventory', 'kind', 'name'), name='uq_inventory_bucket')],
            },
        ),
    ]
